# 필수라이브러리 호출

In [6]:
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from IPython.display import Image

In [2]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

mpl.rc('font', family = 'malgun gothic')
mpl.rc('axes', unicode_minus = False)

sns.set_style('darkgrid')
sns.set(font="malgun gothic")


plt.rc('figure', figsize = (10, 8))
plt.rc('font', family = 'malgun gothic')

warnings.filterwarnings('ignore')

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
np.__version__

'1.20.3'

In [9]:
pd.__version__

'1.3.4'

AttributeError: module 'numpy' has no attribute 'version_'

# 데이터 로딩

In [3]:
data = pd.read_csv('C:/k_digital/source/data/dating.csv')
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,...,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,...,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,...,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,...,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1.0,1
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,...,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,...,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1

In [4]:
# 컬럼 40개까지 표시하는 설정
pd.options.display.max_columns = 40

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   has_null                       8378 non-null   int64
 1   gender                         8378 non-null   object
 2   age                            8283 non-null   float64
 3   age_o                          8274 non-null   float64
 4   race                           8315 non-null   object
 5   race_o                         8305 non-null   object
 6   importance_same_race           8299 non-null   float64
 7   importance_same_religion       8299 non-null   float64
 8   pref_o_attractive              8289 non-null   float64
 9   pref_o_sincere                 8289 non-null   float64
 10  pref_o_intelligence            8289 non-null   float64
 11  pref_o_funny                   8280 non-null   float64
 12  pref_o_ambitious               8271 non-null   float64
 13  pref_o_shared_interests        8249 non-null   float64
 14  attractive_o                   8166 non-null   float64
 15  sincere_o                      8091 non-null   float64
 16  intelligence_o                 8072 non-null   float64
 17  funny_o                        8018 non-null   float64
 18  ambitous_o                     7656 non-null   float64
 19  shared_interests_o             7302 non-null   float64
 20  attractive_important           8299 non-null   float64
 21  sincere_important              8299 non-null   float64
 22  intellicence_important         8299 non-null   float64
 23  funny_important                8289 non-null   float64
 24  ambtition_important            8279 non-null   float64
 25  shared_interests_important     8257 non-null   float64
 26  attractive_partner             8176 non-null   float64
 27  sincere_partner                8101 non-null   float64
 28  intelligence_partner           8082 non-null   float64
 29  funny_partner                  8028 non-null   float64
 30  ambition_partner               7666 non-null   float64
 31  shared_interests_partner       7311 non-null   float64
 32  interests_correlate            8220 non-null   float64
 33  expected_happy_with_sd_people  8277 non-null   float64
 34  expected_num_interested_in_me  1800 non-null   float64
 35  like                           8138 non-null   float64
 36  guess_prob_liked               8069 non-null   float64
 37  met                            8003 non-null   float64
 38  match                          8378 non-null   int64
dtypes: float64(34), int64(2), object(3)
memory usage: 2.5+ MB

In [7]:
# 수치 데이터의 기초 통계량
round(data.describe(), 2)

,has_null,age,age_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
count,8378.00,8283.00,8274.00,8299.00,8299.00,8289.00,8289.00,8289.00,8280.00,8271.00,8249.00,8166.00,8091.00,8072.00,8018.00,7656.00,7302.00,8299.00,8299.00,8299.00,8289.00,8279.00,8257.00,8176.00,8101.00,8082.00,8028.00,7666.00,7311.00,8220.00,8277.00,1800.00,8138.00,8069.00,8003.00,8378.00
mean,0.87,26.36,26.36,3.78,3.65,22.50,17.40,20.27,17.46,10.69,11.85,6.19,7.18,7.37,6.40,6.78,5.47,22.51,17.40,20.27,17.46,10.68,11.85,6.19,7.18,7.37,6.40,6.78,5.47,0.20,5.53,5.57,6.13,5.21,0.05,0.16
std,0.33,3.57,3.56,2.85,2.81,12.57,7.04,6.78,6.09,6.13,6.36,1.95,1.74,1.55,1.95,1.79,2.16,12.59,7.05,6.78,6.09,6.12,6.36,1.95,1.74,1.55,1.95,1.79,2.16,0.30,1.73,4.76,1.84,2.13,0.28,0.37
min,0.00,18.00,18.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.83,1.00,0.00,0.00,0.00,0.00,0.00
25%,1.00,24.00,24.00,1.00,1.00,15.00,15.00,17.39,15.00,5.00,9.52,5.00,6.00,6.00,5.00,6.00,4.00,15.00,15.00,17.39,15.00,5.00,9.52,5.00,6.00,6.00,5.00,6.00,4.00,-0.02,5.00,2.00,5.00,4.00,0.00,0.00
50%,1.00,26.00,26.00,3.00,3.00,20.00,18.37,20.00,18.00,10.00,10.64,6.00,7.00,7.00,7.00,7.00,6.00,20.00,18.18,20.00,18.00,10.00,10.64,6.00,7.00,7.00,7.00,7.00,6.00,0.21,6.00,4.00,6.00,5.00,0.00,0.00
75%,1.00,28.00,28.00,6.00,6.00,25.00,20.00,23.81,20.00,15.00,16.00,8.00,8.00,8.00,8.00,8.00,7.00,25.00,20.00,23.81,20.00,15.00,16.00,8.00,8.00,8.00,8.00,8.00,7.00,0.43,7.00,8.00,7.00,7.00,0.00,0.00
max,1.00,55.00,55.00,10.00,10.00,100.00,60.00,50.00,50.00,53.00,30.00,10.50,10.00,10.00,11.00,10.00,10.00,100.00,60.00,50.00,50.00,53.00,30.00,10.00,10.00,10.00,10.00,10.00,10.00,0.91,10.00,20.00,10.00,10.00,8.00,1.00

## 전처리 - 결측치 제거

In [9]:
data.isna().mean()

has_null                         0.000000
gender                           0.000000
age                              0.011339
age_o                            0.012413
race                             0.007520
race_o                           0.008713
importance_same_race             0.009429
importance_same_religion         0.009429
pref_o_attractive                0.010623
pref_o_sincere                   0.010623
pref_o_intelligence              0.010623
pref_o_funny                     0.011697
pref_o_ambitious                 0.012772
pref_o_shared_interests          0.015397
attractive_o                     0.025304
sincere_o                        0.034256
intelligence_o                   0.036524
funny_o                          0.042970
ambitous_o                       0.086178
shared_interests_o               0.128432
attractive_important             0.009429
sincere_important                0.009429
intellicence_important           0.009429
funny_important                  0.010623
ambtition_important              0.011817
shared_interests_important       0.014443
attractive_partner               0.024111
sincere_partner                  0.033063
intelligence_partner             0.035331
funny_partner                    0.041776
ambition_partner                 0.084984
shared_interests_partner         0.127357
interests_correlate              0.018859
expected_happy_with_sd_people    0.012055
expected_num_interested_in_me    0.785152
like                             0.028646
guess_prob_liked                 0.036882
met                              0.044760
match                            0.000000
dtype: float64

In [10]:
data.columns

Index(['has_null', 'gender', 'age', 'age_o', 'race', 'race_o',
       'importance_same_race', 'importance_same_religion', 'pref_o_attractive',
       'pref_o_sincere', 'pref_o_intelligence', 'pref_o_funny',
       'pref_o_ambitious', 'pref_o_shared_interests', 'attractive_o',
       'sincere_o', 'intelligence_o', 'funny_o', 'ambitous_o',
       'shared_interests_o', 'attractive_important', 'sincere_important',
       'intellicence_important', 'funny_important', 'ambtition_important',
       'shared_interests_important', 'attractive_partner', 'sincere_partner',
       'intelligence_partner', 'funny_partner', 'ambition_partner',
       'shared_interests_partner', 'interests_correlate',
       'expected_happy_with_sd_people', 'expected_num_interested_in_me',
       'like', 'guess_prob_liked', 'met', 'match'],
      dtype='object')

In [12]:
data = data.dropna(subset = ['pref_o_attractive',
       'pref_o_sincere', 'pref_o_intelligence', 'pref_o_funny',
       'pref_o_ambitious', 'pref_o_shared_interests', 'attractive_o',
       'sincere_o', 'intelligence_o', 'funny_o', 'ambitous_o',
       'shared_interests_o', 'attractive_important', 'sincere_important',
       'intellicence_important', 'funny_important', 'ambtition_important',
       'shared_interests_important'])

In [13]:
data = data.fillna(-99)

In [ ]:
# has_null 널값이 있냐 없냐
# gender 성별
# age 내 나이
# age_0 상대 나이
# race 내 인종
# race_0 상대 인종
# importance_same_race 같은 인종을 갖고 있는걸 중요히 여기는 지
# importance_same_religion 같은 종교을 갖고 있는걸 중요히 여기는 지

# 상대가 이 항목(내)을 얼마나 중요하게 생각하는가의 항목
# pref_o_attractive 매력
# pref_o_sincere 성실
# pref_o_intelligence 지적
# pref_o_funny 재미
# pref_o_ambitious 야망
# pref_o_shared_interests 공유 관심사

# 내가 상대의 그 항목을 얼마나 중요하게 생각하는가
# attractive_o 매력
# sincere_o 성실
# intelligence_o 지적
# funny_o 재미
# ambitous_o 야망
# shared_interests_o 공유 관심사

# 자기 자신이 자신을 평가
# attractive_important 매력
# sincere_important 성실
# intellicence_important 지능
# funny_important 재미
# ambtition_important 야망
# shared_interests_important 공유 관심사

# 내가 상대를 평가
# attractive_partner 매력
# sincere_partner 성실
# intelligence_partner 지능
# funny_partner 재미
# ambition_partner 야망
# shared_interests_partner 공유관심사 

# interests_correlate 참가자와 파트너의 관심사간의 상관 관계
# expected_happy_with_sd_people 데이트로 만나는 사람과 얼마나 행복할거라 기대함?
# expected_num_interested_in_me 니가 생각하기에 20명과 만난다면 니랑 사귀고 싶어할 거 같은 사람은 몇명?
# expected_num_matche 얼마나 많은 만남을 가질거라 예상함?
# like 네 파트너 맘에 들었음?
# guess_prob_liked 파트너가 당신을 좋아할 가능성은 얼마라 생각함?
# met 이전에 파트너를 만난적 있음?
# match 매칭 결과

## 전처리 - 피처 엔지니어링

### 나이(내나이와 상대방의 나이)

In [14]:
def age_gap(x):
    if x['age'] == -99: #결측처리가 되어있는 경우
        return -99
    elif x['age_o'] == 99:
        return -99
    elif x['gender'] == 'female':
        return x['age_o'] - x['age']
    else:
        return x['age'] - x['age_o']

- 남녀 중 누구 하나라도 결측일 경우 결츠값 반환
- 남자가 연상이면 +값, 여자가 연상이면 -값

In [15]:
data['age_gap'] = data.apply(age_gap, axis = 1)

### 인종
- 본인과 상대방이 같은 인종이면 1, 그렇지 않으면 -1, 결측값 -99도 존재

In [19]:
def same_race(x):
    if x['race'] == -99:
        return -99
    elif x['race_o'] == -99:
        return -99
    elif x['race'] == x['race_o']:
        return 1
    else:
        return -1

In [20]:
data['same_race'] = data.apply(same_race, axis = 1)

In [21]:
def same_race_point(x):
    if x['same_race'] == -99:
        return -99
    else:
        return x['same_race'] * x['importance_same_race']

In [22]:
data['same_race_point'] = data.apply(same_race_point, axis = 1)

### 평가항목별 점수 환산
- 평가점수 * 중요도

In [23]:
def rating(data, importance, score):
    if data[importance] == -99:
        return -99
    elif data[score] == -99:
        return -99
    else:
        return data[importance] * data[score]

- pref_o_xxx : 상대방이 xxx 항목을 얼마나 중요하게 생각하는지에 대한 응답
- xxx_o : 상대방이 본인에 대한 xxx 항목을 평가한 값
- xxx_importance : xxx 항목에 대해 본인이 얼마나 중요하게 생각하는지에 대한 응답
- xxx_partner : 본인이 상대방에 대한 xxx 항목을 평가한 값

In [ ]:
# 상대방의 중요도

In [24]:
# 'pref_o_attractive','pref_o_sincere', 'pref_o_intelligence', 'pref_o_funny','pref_o_ambitious', 'pref_o_shared_interests'

In [28]:
# 상대방의 중요도
partner_imp = data.columns[8:14]
# 상대방이 본인에 대한 평가
partner_rate_me = data.columns[14:20]
# 본인의 중요도
my_imp = data.columns[20:26]
# 상대방에 대한 본인의 평가
my_rate_partner = data.columns[26:32]

In [29]:
new_partner = ['attractive_p', 'sincere_p', 'intelligence_p', 'funny_p', 'ambition_p', 'shared_interests_p']
new_me = ['attractive_m', 'sincere_m', 'intelligence_m', 'funny_m', 'ambition_m', 'shared_interests_m']

In [30]:
# 상대방 관련 항목 점수
for i, j, k in zip(new_partner, partner_imp, partner_rate_me):
    data[i] = data.apply(lambda x : rating(x, j, k), axis = 1)

In [32]:
# 본인 관련 항목 점수
for i, j, k in zip(new_me, my_imp, my_rate_partner):
    data[i] = data.apply(lambda x : rating(x, j, k), axis = 1)

In [33]:
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,...,expected_num_interested_in_me,like,guess_prob_liked,met,match,age_gap,same_race,same_race_point,attractive_p,sincere_p,intelligence_p,funny_p,ambition_p,shared_interests_p,attractive_m,sincere_m,intelligence_m,funny_m,ambition_m,shared_interests_m
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,...,2.0,7.0,6.0,0.0,0,6.0,-1,-2.0,210.0,160.0,160.0,160.0,0.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,...,2.0,7.0,5.0,1.0,0,1.0,-1,-2.0,420.0,0.0,0.0,280.0,0.0,0.0,105.0,160.0,140.0,120.0,75.0,90.0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,...,2.0,7.0,-99.0,1.0,1,1.0,1,2.0,190.0,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,...,2.0,7.0,6.0,0.0,1,2.0,-1,-2.0,210.0,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,...,2.0,6.0,6.0,0.0,1,3.0,-1,-2.0,240.0,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0

In [35]:
# 더미변수 생성
data = pd.get_dummies(data, columns = ['gender', 'race', 'race_o'], drop_first = True)

In [36]:
data

,has_null,age,age_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,...,sincere_p,intelligence_p,funny_p,ambition_p,shared_interests_p,attractive_m,sincere_m,intelligence_m,funny_m,ambition_m,shared_interests_m,gender_male,race_Black/AfricanAmerican,race_European/Caucasian-American,race_Latino/HispanicAmerican,race_Other,race_o_Black/AfricanAmerican,race_o_European/Caucasian-American,race_o_Latino/HispanicAmerican,race_o_Other
0,0,21.0,27.0,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,...,160.0,160.0,160.0,0.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,0,0,0,0,0,0,1,0,0
1,0,21.0,22.0,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,...,0.0,0.0,280.0,0.0,0.0,105.0,160.0,140.0,120.0,75.0,90.0,0,0,0,0,0,0,1,0,0
2,1,21.0,22.0,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,...,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,0,0,0,0,0,0,0,0,0
3,0,21.0,23.0,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,...,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,0,0,0,0,0,0,1,0,0
4,0,21.0,24.0,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,...,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8372,1,25.0,24.0,1.0,1.0,10.0,15.0,30.0,20.0,15.0,10.0,8.0,8.0,7.0,7.0,8.0,6.0,70.0,0.0,15.0,...,120.0,210.0,140.0,120.0,60.0,490.0,0.0,75.0,75.0,0.0,-99.0,1,0,1,0,0,0,1,0,0
8373,1,25.0,26.0,1.0,1.0,10.0,10.0,30.0,20.0,10.0,15.0,10.0,5.0,3.0,2.0,6.0,5.0,70.0,0.0,15.0,...,50.0,90.0,40.0,60.0,75.0,210.0,0.0,75.0,75.0,-99.0,-99.0,1,0,1,0,0,0,0,1,0
8374,1,25.0,24.0,1.0,1.0,50.0,20.0,10.0,5.0,10.0,5.0,6.0,3.0,7.0,3.0,7.0,2.0,70.0,0.0,15.0,...,60.0,70.0,15.0,70.0,10.0,280.0,0.0,120.0,60.0,0.0,-99.0,1,0,1,0,0,0,0,0,1
8376,1,25.0,22.0,1.0,1.0,10.0,25.0,25.0,10.0,10.0,20.0,5.0,7.0,5.0,5.0,3.0,6.0,70.0,0.0,15.0,...,175.0,125.0,50.0,30.0,120.0,280.0,0.0,75.0,60.0,-99.0,0.0,1,0,1,0,0,0,0,0,0
8377,1,25.0,22.0,1.0,1.0,20.0,20.0,10.0,15.0,5.0,30.0,8.0,8.0,7.0,7.0,7.0,7.0,70.0,0.0,15.0,...,160.0,70.0,105.0,35.0,210.0,210.0,0.0,90.0,60.0,0.0,0.0,1,0,1,0,0,0,0,0,0

# 모델링과 평가

## 훈련세트와 테스트세트 분리

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.drop('match', axis = 1), 
                                                    data['match'], test_size = 0.2, random_state = 100)

## 모델링과 평가

In [38]:
import xgboost as xgb

model = xgb.XGBClassifier(n_estimators = 500, max_depth = 5, random_state = 100)
model.fit(X_train, y_train)
pred = model.predict(X_test)

In [39]:
pred

array([0, 0, 0, ..., 0, 1, 0])

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test, pred)

0.8367496339677891

In [42]:
print(confusion_matrix(y_test, pred))

[[1041   73]
 [ 150  102]]

In [43]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90      1114
           1       0.58      0.40      0.48       252

    accuracy                           0.84      1366
   macro avg       0.73      0.67      0.69      1366
weighted avg       0.82      0.84      0.82      1366

In [44]:
## 그리드서치 및 하이퍼파라미터 값을 조정하여 => 타깃 '1'이 더 도출되도록 유도 => 매칭되는(1) 주요 특성을 찾아낼수 있음

## 하이퍼파라미터 튜닝 : 그리드 서치

In [45]:
from sklearn.model_selection import GridSearchCV

In [47]:
parameters = {
    'learning_rate' : [0.01, 0.1, 0.3],
    'max_depth' : [5, 7, 10],
    'subsample' : [0.5, 0,7, 1],
    'n_estimators' : [300, 500, 1000]
}

In [50]:
model = xgb.XGBClassifier()

gs = GridSearchCV(model, parameters, n_jobs = -1, scoring = 'f1', cv = 5)
gs.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.3],
                         'max_depth': [5, 7, 10],
                         'n_estimators': [300, 500, 1000],
                         'subsample': [0.5, 0, 7, 1]},
             scoring='f1')

In [51]:
gs.best_params_

{'learning_rate': 0.3, 'max_depth': 5, 'n_estimators': 1000, 'subsample': 1}

NameError: name 'df' is not defined

NameError: name 'mpl' is not defined